### PR TITLE
All basic Features mocking-up the newsweek page

### PR DESCRIPTION
**Pull request by NewIncome**
**What was done:**
- Initialized the repo, created the HTML and the CSS files
- Fixeded the navbar and added the first 3 sections only for the mobile version
- Added 3 sections complete with styles, feat-stories, op & latest news
- Finished more sections, in-the-magazine and editors pick
- Finished the litltle red-double-square
- added the last red-triple-little-square
- Added the section editors pick and started the separate sections
- Finished the U.S. section
- added the remaining 6 sections similar to u.s.
- Finished subscribe+newsletter section
- added footer top part w-resp and some minor fixes to upper section
- Added footer with responsiveness. Todo, whole responsiveness.
- Added responsiveness to the subscribe+newsletter and repeated u.s. secs
- added responsiveness to featured-slideshows n editors-pick secs
- fix in resp 4 eds-pick, added responsive 4 inTmag sec
- Added remaining responsiveness, 4 the main section
- fixed a minor view like on opinion and rounded corners on some sections
- Added navbar finished and responsiveness
- fixed validator errors and readme file
- added poligon effect to navbar

### CODE REVIEW

**Comment by suretrust** [comment]
**Great job thus far :raised_hands: @NewIncome,**

Just a few necessary amendments:

1. The navigation bar does not display the Newsweek logo on a large screen as shown below.
logo-large-screen
2. Linter is not properly setup. It should display as shown below when properly setup.
linter2
3. Your readme could be better. You can check [this repo](https://github.com/othneildrew/Best-README-Template) for reference.

**Please submit for another code review once these issues have been fixed. Good luck. :tada:**

**Comment by alissonperes** [comment]
@suretrust  For a really simple project, that only uses BOOTSTRAP, HTML and CSS is it really expected to create an insane README.md file with so many usless information? This is a simple project, that won't be forked, or worked on in the future. I agree that, once we get to RoR we would need a very descriptive readme file, even better than the one sent in the link, but right now, it's completely useless.

**Comment by shshamim63** [comment]
### Changes Required!
___
Hi @NewIncome  :wave:
Awesome job. Well for sure I can say that, you are almost done. But to declare this project as complete, one point is just blocking me,
___
### Mandatory Changes!
1. The navbar for the mobile version does not seem right. Please fix this.
___
##### -> Original page
bootstrapactual
 ##### -> This project
bootstrapyourone

___
#### Please Fix the mentioned issues and send another review request.
___
##### Happy Coding
##### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawat-hossain-7750b0127/)| [Slack](Shakhawat Hossain)

**Review by Forison — COMMENTED** [review]
# pull request under review by ADDO

**Review by Forison — APPROVED** [review]
# God Job @Alfredo👋👋
You have successfully implemented the changes suggested earlier.
Your project is amazing 👌
#### Go ahead and merge to master and proceed to the next project💪
# project approved💪💪💪
Happy coding🙂

**Pull request merged**
